- name: copy sshtrust to nodes
  copy:
    src: /root/system-install-and-config/sshtrust  
    dest: /root/sshtrust
    mode: preserve

- name: execute sshtrust-mutual.sh
  shell: bash /root/sshtrust/sshtrust-mutual.sh
    
