- name: copy sshtrust to nodes
  copy:
    src: /root/system-install-and-config/sshtrust  
    dest: /root
    mode: preserve

- name: execute sshtrust.sh
  shell: 
    cmd: bash sshtrust.sh
    chdir: /root/sshtrust
    
