- name: install rabbitmq cluster
  remote_user: root
  hosts: rabbitmq
  tasks:
    - name: copy rabbit directory to rabbitmq nodes
      copy:
        src: /root/system-install-and-config/rabbitmq/rabbitmq-install
        dest: /root/system-install-and-config/rabbitmq
        mode: preserve
    
    - name: execute rabbitmq-master-install.sh in master node
      shell:
        cmd: bash rabbitmq-master-install.sh
        chdir: /root/system-install-and-config/rabbitmq/rabbitmq-install
      delegate_to: "{{ item }}"
      run_once: true
      with_items: "{{ groups.rabbitmq_master }}"
    
    - name: execute rabbitmq-slave-install.sh in slave nodes
      shell:
        cmd: bash rabbitmq-slave-install.sh
        chdir: /root/system-install-and-config/rabbitmq/rabbitmq-install
      delegate_to: "{{ item }}"
      run_once: true
      with_items: "{{ groups.rabbitmq_slave }}"

- name: install haproxy 
  remote_user: root
  hosts: haproxy
  tasks:
    - name: copy haproxy-install directory to haproxy nodes
      copy:
        src: /root/system-install-and-config/rabbitmq/haproxy-install
        dest: /root/system-install-and-config/rabbitmq
        mode: preserve
    
    - name: execute haproxy-install.sh
      shell:
        cmd: bash haproxy-install.sh
        chdir: /root/system-install-and-config/rabbitmq/haproxy-install

- name: install keepalived
  hosts: keepalived
  remote_user: root
  roles:
    - role: keepalived

