version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    restart: always
    privileged: true
    ports:
      - 2181:2181
    volumes:
      - /mydata/zookeeper/conf:/zookeeper-3.4.9/conf
      - /mydata/zookeeper/data:/zookeeper-3.4.9/data
      - /mydata/zookeeper/logs:/zookeeper-3.4.9/logs
      - /etc/localtime:/etc/localtime

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    privileged: true
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://120.27.215.93:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9988
    depends_on:
      - zookeeper #kafka在zookeeper之后启动
    volumes:
      - /etc/localtime:/etc/localtime

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - /etc/localtime:/etc/localtime

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    restart: always    
    user: root
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
      - /etc/localtime:/etc/localtime
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: logstash:7.6.2
    container_name: logstash
    restart: always    
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动

  kibana:
    image: kibana:7.6.2
    container_name: kibana
    restart: always    
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
    volumes:
      - /etc/localtime:/etc/localtime
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/mysql/log:/var/log/mysql #日志文件挂载

  redis:
    image: redis:5
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
